### ISSUE TITLE
Can I get your test-data??

### ISSUE THREAD

**Issue by edwardcho** [hyperconnect/LADE#7]
Hello Sir,

I checked your testing result in your notebook-directory.
(ImageNet-LT)

![image](https://user-images.githubusercontent.com/29569662/117258661-28e7d780-ae88-11eb-966c-74c31acf39d9.png)

I want to get all files of 'lade21-lade'.
Can I get this files??

Thanks.
Edward Cho.

**Comment by juice500ml** [comment]
Hi! You can obtain the *.npy files after you train the model. Thank you for your interest to our paper!
